include:
  - board: nice_nano
    shield: lily58_left lpm_view_adapter lpm_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano
    shield: lily58_right





